[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = min_spiffs.csv
monitor_speed = 115200
extra_scripts = pre:scripts/embed_html.py
lib_deps =
    bblanchon/ArduinoJson@^7
    adafruit/Adafruit NeoPixel@^1.12
