"""Pre-build script: embeds web/*.html files into include/html_templates.h as C++ constants."""

import os
import glob

Import("env")

project_dir = env["PROJECT_DIR"]
web_dir = os.path.join(project_dir, "web")
out_path = os.path.join(project_dir, "include", "html_templates.h")

html_files = sorted(glob.glob(os.path.join(web_dir, "*.html")))
if not html_files:
    print("embed_html: no HTML files found in web/")
else:
    lines = [
        "#pragma once",
        "// Auto-generated by scripts/embed_html.py — do not edit manually",
        "",
    ]

    for filepath in html_files:
        name = os.path.splitext(os.path.basename(filepath))[0]
        var_name = "HTML_" + name.upper().replace("-", "_")

        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()

        lines.append(f'const char {var_name}[] PROGMEM = R"HTMLRAW({content})HTMLRAW";')
        lines.append("")

    header = "\n".join(lines)

    # Only write if content changed (avoid unnecessary rebuilds)
    write = True
    if os.path.exists(out_path):
        with open(out_path, "r", encoding="utf-8") as f:
            if f.read() == header:
                write = False

    if write:
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(header)
        print(f"embed_html: generated {out_path} from {len(html_files)} file(s)")
